import streamlit as st
from datetime import datetime
import pandas as pd
import requests

# --- CONFIGURAÇÃO DA PÁGINA ---
st.set_page_config(page_title="Controle de Manutenção & PT", layout="wide", page_icon="⚙️")

# --- CONEXÃO BLINDADA VIA API REST (HTTP) COM O SUPABASE ---
@st.cache_resource
def obter_credenciais():
    """Recupera e limpa as credenciais dos Secrets."""
    try:
        url = st.secrets["supabase"]["url"].strip().rstrip("/")
        key = st.secrets["supabase"]["key"].strip()
        return url, key
    except Exception as e:
        st.error(f"Erro ao ler os Secrets no Streamlit: {e}")
        return None, None

SUBAPASE_URL, SUPABASE_KEY = obter_credenciais()

# --- INSTALADOR AUTOMÁTICO DE TABELAS VIA SQL GATEWAY (SUPABASE) ---
@st.cache_resource
def criar_estruturas_no_supabase():
    """Cria automaticamente as tabelas estruturadas via API REST caso elas não existam."""
    if not SUBAPASE_URL or not SUPABASE_KEY:
        return
    
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json"
    }
    
    # Script SQL Industrial para execução via API RPC nativa do Supabase
    sql_query = """
    CREATE TABLE IF NOT EXISTS maquinas (
        id TEXT PRIMARY KEY,
        nome TEXT,
        localizacao TEXT,
        criticidade TEXT,
        check_semanal TEXT,
        check_mensal TEXT,
        check_anual TEXT
    );
    CREATE TABLE IF NOT EXISTS planejamento (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        equipamento TEXT,
        periodo TEXT,
        data_prevista TEXT,
        pecas TEXT,
        status TEXT,
        seguranca TEXT
    );
    CREATE TABLE IF NOT EXISTS historico (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        equipamento TEXT,
        periodo TEXT,
        data_prevista TEXT,
        data_conclusao TEXT,
        pecas TEXT,
        status TEXT
    );
    """
    url_rpc = f"{SUBAPASE_URL}/rest/v1/rpc/sql"
    try:
        # Tenta executar a criação automática via Gateway SQL do Supabase
        requests.post(url_rpc, headers=headers, json={"query": sql_query})
    except Exception:
        pass

# Executa o instalador de tabelas em segundo plano
criar_estruturas_no_supabase()

# --- FUNÇÕES DE INTERAÇÃO DIRETA COM O BANCO DE DADOS (API REST) ---
def buscar_dados(tabela: str):
    """Busca dados diretamente via REST API do Supabase."""
    if not SUBAPASE_URL or not SUPABASE_KEY:
        return []
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}"
    }
    url = f"{SUBAPASE_URL}/rest/v1/{tabela}?select=*"
    try:
        response = requests.get(url, headers=headers)
        if response.status_code == 200:
            return response.json()
    except Exception:
        pass
    return []

def inserir_dados(tabela: str, payload: dict):
    """Insere um novo registro diretamente via REST API."""
    if not SUBAPASE_URL or not SUPABASE_KEY:
        return False
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal"
    }
    url = f"{SUBAPASE_URL}/rest/v1/{tabela}"
    try:
        response = requests.post(url, headers=headers, json=payload)
        return 200 <= response.status_code <= 299
    except Exception:
        return False

def atualizar_dados(tabela: str, payload: dict, coluna_id: str, valor_id):
    """Atualiza um registro diretamente via REST API."""
    if not SUBAPASE_URL or not SUPABASE_KEY:
        return False
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}",
        "Content-Type": "application/json",
        "Prefer": "return=minimal"
    }
    url = f"{SUBAPASE_URL}/rest/v1/{tabela}?{coluna_id}=eq.{valor_id}"
    try:
        response = requests.patch(url, headers=headers, json=payload)
        return 200 <= response.status_code <= 299
    except Exception:
        return False

def excluir_dados(tabela: str, coluna_id: str, valor_id):
    """Exclui um registro diretamente via REST API."""
    if not SUBAPASE_URL or not SUPABASE_KEY:
        return False
    headers = {
        "apikey": SUPABASE_KEY,
        "Authorization": f"Bearer {SUPABASE_KEY}"
    }
    url = f"{SUBAPASE_URL}/rest/v1/{tabela}?{coluna_id}=eq.{valor_id}"
    try:
        response = requests.delete(url, headers=headers)
        return 200 <= response.status_code <= 299
    except Exception:
        return False

# Estados de controle para edição ativa
if "editando_maquina_id" not in st.session_state:
    st.session_state.editando_maquina_id = None
if "editando_os_id" not in st.session_state:
    st.session_state.editando_os_id = None

# --- MENU LATERAL ---
st.sidebar.markdown("**Desenvolvido por GDCOM**")
st.sidebar.title("⚙️ Gestão de Manutenção")
menu = st.sidebar.radio("Navegar para:", [
    "🔍 Abas 1 & 2: Gerenciar Máquinas",
    "📅 Aba 3: Ordens de Serviço (OS)",
    "📜 Aba 4: Histórico de Trocas",
    "⚠️ Aba 5: Emissão de PT"
])

# Carregamento dinâmico e direto das tabelas estruturadas
equipamentos = buscar_dados("maquinas")
todos_agendamentos = buscar_dados("planejamento")
historico_lista = buscar_dados("historico")

# Injeção automática de dados de teste caso as novas tabelas do Supabase estejam recém-criadas e vazias
if menu == "🔍 Abas 1 & 2: Gerenciar Máquinas" and not equipamentos:
    inserir_dados("maquinas", {"id": "EQ-001", "nome": "Torno Mecânico Nardini", "localizacao": "Oficina Central", "criticidade": "Alta", "check_semanal": "1. Verificar nível de óleo.", "check_mensal": "1. Trocar filtros.", "check_anual": "1. Revisão motor."})
    inserir_dados("maquinas", {"id": "EQ-002", "nome": "Compressor de Ar Schulz", "localizacao": "Sala Compressores", "criticidade": "Média", "check_semanal": "1. Drenar reservatório.", "check_mensal": "1. Limpar conexões.", "check_anual": "1. Teste válvula."})
    st.rerun()

# ==========================================
# ABAS 1 & 2: GERENCIAR MÁQUINAS
# ==========================================
if menu == "🔍 Abas 1 & 2: Gerenciar Máquinas":
    st.header("🔍 Gerenciamento de Equipamentos")
    
    if st.session_state.editando_maquina_id is not None:
        st.subheader("✏️ Editar Equipamento Registrado")
        mq_editar = next((m for m in equipamentos if str(m["id"]) == str(st.session_state.editando_maquina_id)), None)
        
        if mq_editar:
            with st.form("form_editar_maquina"):
                edit_nome = st.text_input("Nome do Equipamento:", value=mq_editar.get("nome", ""))
                edit_local = st.text_input("Localização / Setor:", value=mq_editar.get("localizacao", ""))
                edit_crit = st.selectbox("Criticidade:", ["Baixa", "Média", "Alta"], index=["Baixa", "Média", "Alta"].index(mq_editar.get("criticidade", "Baixa")))
                edit_sem = st.text_area("Checklist Semanal:", value=mq_editar.get("check_semanal", ""))
                edit_mes = st.text_area("Checklist Mensal:", value=mq_editar.get("check_mensal", ""))
                edit_ano = st.text_area("Checklist Anual:", value=mq_editar.get("check_anual", ""))
                
                col_m1, col_m2 = st.columns(2)
                with col_m1: btn_salvar_mq = st.form_submit_button("💾 Salvar Alterações")
                with col_m2: btn_canc_mq = st.form_submit_button("❌ Cancelar")
                
            if btn_salvar_mq:
                payload = {"nome": edit_nome, "localizacao": edit_local, "criticidade": edit_crit, "check_semanal": edit_sem, "check_mensal": edit_mes, "check_anual": edit_ano}
                atualizar_dados("maquinas", payload, "id", mq_editar["id"])
                st.session_state.editando_maquina_id = None
                st.success("🎉 Equipamento atualizado com sucesso no Supabase!")
                st.rerun()
            if btn_canc_mq:
                st.session_state.editando_maquina_id = None
                st.rerun()
    else:
        st.subheader("➕ Cadastrar Nova Máquina")
        with st.form("form_cadastro_direto"):
            id_eq = st.text_input("Tag do Equipamento (Ex: EQ-003):")
            nome_eq = st.text_input("Nome do Equipamento:")
            local_eq = st.text_input("Localização / Setor:")
            crit_eq = st.selectbox("Criticidade:", ["Baixa", "Média", "Alta"])
            st.markdown("##### 📜 Ações Preventivas")
            c_sem = st.text_area("Checklist Semanal:", "1. Verificar nível de óleo; 2. Limpeza.")
            c_mes = st.text_area("Checklist Mensal:", "1. Troca de filtros.")
            c_ano = st.text_area("Checklist Anual:", "1. Revisão preventiva.")
            botao_salvar = st.form_submit_button("Salvar Novo Equipamento")
            
        if botao_salvar and id_eq and nome_eq:
            payload = {"id": id_eq, "nome": nome_eq, "localizacao": local_eq, "criticidade": crit_eq, "check_semanal": c_sem, "check_mensal": c_mes, "check_anual": c_ano}
            inserir_dados("maquinas", payload)
            st.success("🎉 Equipamento salvo diretamente no Supabase!")
            st.rerun()

    st.markdown("---")
    st.subheader("📋 Lista de Equipamentos Registrados")
    if not equipamentos:
        st.info("Nenhuma máquina encontrada na tabela 'maquinas' do Supabase.")
    else:
        for mq in equipamentos:
            st.write(f"🔹 **[{mq.get('id')}] {mq.get('nome')}** | Setor: {mq.get('localizacao')} | Criticidade: {mq.get('criticidade')}")
            c_m1, c_m2 = st.columns(2)
            with c_m1:
                if st.button(f"✏️ Editar {mq.get('id')}", key=f"ed_mq_{mq.get('id')}"):
                    st.session_state.editando_maquina_id = mq.get('id')
                    st.rerun()
            with c_m2:
                if st.button(f"🗑️ Excluir {mq.get('id')}", key=f"ex_mq_{mq.get('id')}"):
                    excluir_dados("maquinas", "id", mq.get('id'))
